name: CI

on:
  push:
    branches:
      - main
      - ci-raw-facade
      - ci-github-actions
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.1']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none
          tools: composer:v2
          extensions: curl, json

      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: |
            ~/.composer/cache
            vendor
          key: composer-${{ runner.os }}-${{ matrix.php-version }}-${{ hashFiles('composer.lock') }}

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --no-progress --no-ansi

      - name: PHPUnit
        run: vendor/bin/phpunit --testsuite unit --display-errors

      - name: PHP CS Fixer
        run: vendor/bin/php-cs-fixer fix --dry-run --diff --config=.php-cs-fixer.php --sequential

      - name: PHPStan
        run: vendor/bin/phpstan analyse --configuration=phpstan.neon --no-progress --memory-limit=1G

      - name: Rector
        run: vendor/bin/rector process --dry-run --config=rector.php
